rewrite vscode-deno
justjavac/vscode-deno pull request #64
Opened 2020-01-18 08:06 UTC by axetroy

Almost complete rewrite including:

- Restructure the code
- Remove unnecessary configuration
- Remove unnecessary commands
- Remove unnecessary files
- fix bugs
- remove `deno.fmtOnSave` configuration

2020-01-18 09:43 UTC, axetroy commented
/cc @justjavac It's ready for review

2020-01-19 06:12 UTC, axetroy commented on package.json
> +      "[typescriptreact]": {
Controversial here

Do we need to set the default Formatter?

2020-01-23 18:49 UTC, brandonkal requested changes

2020-01-23 18:49 UTC, brandonkal commented on src/utils.ts
> +  return promisify(stat)(filepath)
No need for promisify. Just use
https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fspromises_stat_path_options which is available in Electron's Node.

2020-01-23 18:49 UTC, brandonkal commented on README.md
Remove excess whitespace

2020-01-23 18:49 UTC, brandonkal commented on package.json
> +    "typescript": "^3.7.5",
Current VSCode isn't at 3.7.5 yet.

2020-01-23 18:49 UTC, brandonkal commented on src/extension.ts
> +import { promisify } from "util";
Prefer native fs promises API

2020-01-23 20:19 UTC, brandonkal commented
@axetroy In addition to what I've mentioned, the ISSUE_TEMPLATE directory is failing the defined `yarn run check` step.

2020-01-24 02:58 UTC, axetroy commented
I have built a new version for this, download it here
https://github.com/axetroy/vscode-deno/releases

2020-01-24 10:05 UTC, David-Else commented
@axetroy If there are going to be week long delays in getting pull requests merged on this repo why not start a new VS Code Market place extension? As this is a total re-write it seems logical to re-start it at 1.0?

It would make sense for all the deno contributors to get together and decide which is the 'official' version and link that on the main site. Right now the download stats for different extensions are:

https://marketplace.visualstudio.com/search?term=deno&target=VSCode&category=All%20categories&sortBy=Relevance

3.2k for this one vs 916 and 440 for the others.When Deno 1.0 comes out whatever extension is linked on the main page would soon become the predominant one. It makes no sense to have different competing versions.

I think Deno's adoption will be very much linked to the VS Code extension. Nearly everyone uses VS Code these days, once Deno starts becoming successful then any problems with the extension will stop people using Deno. Ideally it would have more than one person with the authority to update it.

Massive thanks to justjavac for all the work he has done!!

2020-01-24 12:03 UTC, axetroy commented
@David-Else 

ham. I actually have permission to merge this PR. And release a new version

But no permission to publish to vscode market.

I did plan to release another extension before and maintained by [denolib](https://github.com/denolib)

Integrate typescript-vscode-plugin together in the extension for easy maintenance

I am trying to do this.

2020-01-24 12:50 UTC, brandonkal commented
I'm for that. Currently using a locally built version with this PR plus my PR on the TS extension. It still makes sense to publish the TS package as its own npm package but it would be cool to have them live in the same repo. See my PR on the other repo, it fixes a problem with other extensions. 

Haven't found a solution to the other bug:
`import a from "http://a.com/?broken.yaml.js"` freezes the extension. Deno doesn't like the URL either (bug) so I've changed the server to not use a query param but it would still be nice to see that not freeze the editor.

2020-01-24 15:14 UTC, axetroy commented
I have publish a new extension to vscode market https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno

I will try to solve problems in the new repo.

This PR is no longer updated. thanks you all.

close.

2020-01-24 15:14 UTC, closed without merging